version: '2'
services:
  app:
    container_name: user-api
    build:
        context: .
        dockerfile: DockerFile
    ports:
      - 80:3001
    links:
      - mongo
  mongo:
    container_name: mongodbtraffic
    image: mongo
    ports:
      - "27017:27017"
